/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations['me_api_v1_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Patients */
    get: operations['list_patients_api_v1_patients_get'];
    put?: never;
    /** Create Patient */
    post: operations['create_patient_api_v1_patients_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/{patient_id}/activate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate Patient */
    post: operations['activate_patient_api_v1_patients__patient_id__activate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/setup-account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Setup Account */
    post: operations['setup_account_api_v1_patients_setup_account_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/{patient_id}/medications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Patient Medications */
    get: operations['list_patient_medications_api_v1_patients__patient_id__medications_get'];
    put?: never;
    /** Create Patient Medication */
    post: operations['create_patient_medication_api_v1_patients__patient_id__medications_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/medications/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Current Medications */
    get: operations['list_current_medications_api_v1_medications_current_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/medications/{medication_id}/adherence': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Adherence Log */
    post: operations['create_adherence_log_api_v1_medications__medication_id__adherence_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/{patient_id}/adherence': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Patient Adherence Logs */
    get: operations['list_patient_adherence_logs_api_v1_patients__patient_id__adherence_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/patients/{patient_id}/questionnaires': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Patient Questionnaires */
    get: operations['list_patient_questionnaires_api_v1_patients__patient_id__questionnaires_get'];
    put?: never;
    /** Create Patient Questionnaire Assignment */
    post: operations['create_patient_questionnaire_assignment_api_v1_patients__patient_id__questionnaires_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/questionnaires/pending': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Pending Questionnaires */
    get: operations['list_pending_questionnaires_api_v1_questionnaires_pending_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/questionnaires/{assignment_id}/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Questionnaire */
    post: operations['submit_questionnaire_api_v1_questionnaires__assignment_id__submit_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActivatePatientResponse */
    ActivatePatientResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Active */
      is_active: boolean;
      /**
       * Onboarding Status
       * @enum {string}
       */
      onboarding_status: 'pending' | 'completed';
    };
    /** AdherenceLogItem */
    AdherenceLogItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Medication Id
       * Format: uuid
       */
      medication_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'taken' | 'missed' | 'modified';
      /** Deviation Note */
      deviation_note: string | null;
      /**
       * Logged At
       * Format: date-time
       */
      logged_at: string;
    };
    /** AdherenceLogListResponse */
    AdherenceLogListResponse: {
      /** Items */
      items: components['schemas']['AdherenceLogItem'][];
    };
    /** CreateAdherenceLogRequest */
    CreateAdherenceLogRequest: {
      /**
       * Status
       * @enum {string}
       */
      status: 'taken' | 'missed' | 'modified';
      /** Deviation Note */
      deviation_note?: string | null;
      /** Logged At */
      logged_at?: string | null;
    };
    /** CreateMedicationRequest */
    CreateMedicationRequest: {
      /** Name */
      name: string;
      /** Dosage Instructions */
      dosage_instructions: string;
      /**
       * Is Active
       * @default true
       */
      is_active: boolean;
    };
    /** CreatePatientRequest */
    CreatePatientRequest: {
      /** Email */
      email: string;
    };
    /** CreatePatientResponse */
    CreatePatientResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /**
       * Doctor User Id
       * Format: uuid
       */
      doctor_user_id: string;
      /**
       * Onboarding Status
       * @constant
       */
      onboarding_status: 'pending';
      /** Temporary Password */
      temporary_password: string;
    };
    /** CreateQuestionnaireAssignmentRequest */
    CreateQuestionnaireAssignmentRequest: {
      /**
       * Questionnaire Code
       * @enum {string}
       */
      questionnaire_code: 'PHQ-9' | 'GAD-7';
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** LogoutResponse */
    LogoutResponse: {
      /**
       * Message
       * @default logged out
       */
      message: string;
    };
    /** MedicationItem */
    MedicationItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Dosage Instructions */
      dosage_instructions: string;
      /** Is Active */
      is_active: boolean;
    };
    /** MedicationListResponse */
    MedicationListResponse: {
      /** Items */
      items: components['schemas']['MedicationItem'][];
    };
    /** MedicationOut */
    MedicationOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Dosage Instructions */
      dosage_instructions: string;
      /** Is Active */
      is_active: boolean;
      /**
       * Patient User Id
       * Format: uuid
       */
      patient_user_id: string;
      /**
       * Doctor User Id
       * Format: uuid
       */
      doctor_user_id: string;
    };
    /** PatientRosterItem */
    PatientRosterItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Is Active */
      is_active: boolean;
      /**
       * Onboarding Status
       * @enum {string}
       */
      onboarding_status: 'pending' | 'completed';
    };
    /** PatientRosterResponse */
    PatientRosterResponse: {
      /** Items */
      items: components['schemas']['PatientRosterItem'][];
    };
    /** PendingQuestionnaireItem */
    PendingQuestionnaireItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Questionnaire Code
       * @enum {string}
       */
      questionnaire_code: 'PHQ-9' | 'GAD-7';
      /**
       * Status
       * @constant
       */
      status: 'assigned';
      /**
       * Assigned At
       * Format: date-time
       */
      assigned_at: string;
    };
    /** PendingQuestionnaireListResponse */
    PendingQuestionnaireListResponse: {
      /** Items */
      items: components['schemas']['PendingQuestionnaireItem'][];
    };
    /** QuestionnaireAssignmentItem */
    QuestionnaireAssignmentItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Questionnaire Code
       * @enum {string}
       */
      questionnaire_code: 'PHQ-9' | 'GAD-7';
      /**
       * Status
       * @enum {string}
       */
      status: 'assigned' | 'completed';
      /**
       * Assigned At
       * Format: date-time
       */
      assigned_at: string;
      /** Completed At */
      completed_at: string | null;
      /** Total Score */
      total_score?: number | null;
      /** Has Safety Signal */
      has_safety_signal?: boolean | null;
    };
    /** QuestionnaireAssignmentListResponse */
    QuestionnaireAssignmentListResponse: {
      /** Items */
      items: components['schemas']['QuestionnaireAssignmentItem'][];
    };
    /** QuestionnaireAssignmentOut */
    QuestionnaireAssignmentOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Patient User Id
       * Format: uuid
       */
      patient_user_id: string;
      /**
       * Doctor User Id
       * Format: uuid
       */
      doctor_user_id: string;
      /**
       * Questionnaire Code
       * @enum {string}
       */
      questionnaire_code: 'PHQ-9' | 'GAD-7';
      /**
       * Status
       * @enum {string}
       */
      status: 'assigned' | 'completed';
      /**
       * Assigned At
       * Format: date-time
       */
      assigned_at: string;
    };
    /** QuestionnaireSubmissionResult */
    QuestionnaireSubmissionResult: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Assignment Id
       * Format: uuid
       */
      assignment_id: string;
      /**
       * Questionnaire Code
       * @enum {string}
       */
      questionnaire_code: 'PHQ-9' | 'GAD-7';
      /** Total Score */
      total_score: number;
      /** Has Safety Signal */
      has_safety_signal: boolean;
      /**
       * Submitted At
       * Format: date-time
       */
      submitted_at: string;
    };
    /** SetupAccountRequest */
    SetupAccountRequest: {
      /** New Password */
      new_password: string;
    };
    /** SubmitQuestionnaireRequest */
    SubmitQuestionnaireRequest: {
      /** Answers */
      answers: {
        [key: string]: number;
      };
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Role */
      role: string;
      /** Is Active */
      is_active: boolean;
      /** Onboarding Status */
      onboarding_status?: ('pending' | 'completed') | null;
      /** Must Change Password */
      must_change_password?: boolean | null;
      /** Doctor User Id */
      doctor_user_id?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LogoutResponse'];
        };
      };
    };
  };
  list_patients_api_v1_patients_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatientRosterResponse'];
        };
      };
    };
  };
  create_patient_api_v1_patients_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePatientRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreatePatientResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  activate_patient_api_v1_patients__patient_id__activate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        patient_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ActivatePatientResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  setup_account_api_v1_patients_setup_account_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetupAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_patient_medications_api_v1_patients__patient_id__medications_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        patient_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MedicationListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_patient_medication_api_v1_patients__patient_id__medications_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        patient_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateMedicationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MedicationOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_current_medications_api_v1_medications_current_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MedicationListResponse'];
        };
      };
    };
  };
  create_adherence_log_api_v1_medications__medication_id__adherence_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        medication_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAdherenceLogRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdherenceLogItem'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_patient_adherence_logs_api_v1_patients__patient_id__adherence_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        patient_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdherenceLogListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_patient_questionnaires_api_v1_patients__patient_id__questionnaires_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        patient_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionnaireAssignmentListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_patient_questionnaire_assignment_api_v1_patients__patient_id__questionnaires_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        patient_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateQuestionnaireAssignmentRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionnaireAssignmentOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_pending_questionnaires_api_v1_questionnaires_pending_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PendingQuestionnaireListResponse'];
        };
      };
    };
  };
  submit_questionnaire_api_v1_questionnaires__assignment_id__submit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assignment_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmitQuestionnaireRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionnaireSubmissionResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
